# Generated by Django 5.0.1 on 2024-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='homeaddr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ssn',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
