# Generated by Django 5.0.1 on 2024-02-04 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_person_homeaddr_remove_person_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.date(2004, 1, 1)),
        ),
    ]
