# Generated by Django 5.0.1 on 2024-02-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bicycles', '0002_alter_bicycle_price'),
        ('customers', '0003_alter_customer_discount'),
        ('employees', '0003_employee_homeaddr_employee_passport_employee_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemssold', models.IntegerField()),
                ('sale_date', models.DateField()),
                ('subtotal', models.FloatField(editable=False)),
                ('totalcost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycles.bicycle')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
