# Generated by Django 5.0.1 on 2024-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='authority',
            field=models.CharField(choices=[('sales', 'Sales'), ('service', 'Service'), ('manager', 'Manager')], default='sales', max_length=10),
        ),
    ]
