# Generated by Django 5.0.1 on 2024-03-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_homeaddr_employee_passport_employee_role_and_more'),
        ('sales', '0002_sale_warranty_end_alter_sale_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_startdate', models.DateField()),
                ('service_enddate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('service_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, max_length=15, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
            ],
        ),
    ]
