# Generated by Django 5.0.1 on 2024-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='homeaddr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ssn',
            field=models.IntegerField(default='000000000000', unique=True),
        ),
    ]
