# Generated by Django 5.0.1 on 2024-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('bicycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=15, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('modelyear', models.IntegerField()),
                ('type', models.CharField(max_length=15, null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('instock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
