# Generated by Django 5.0.1 on 2024-02-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='price',
            field=models.FloatField(),
        ),
    ]
